### ISSUE TITLE
Can not import the module

### ISSUE THREAD

**Issue by aasiutin** [imazen/imageflow-node#7]
Hi

When I'm trying to load the module I get the next error

```
$ node
> const imageflow = require('@imazen/imageflow')
Uncaught:
Error: Cannot find module '/app/node_modules/@imazen/imageflow/dist/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:329:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:690:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1017:27)
    at Function.Module._load (internal/modules/cjs/loader.js:899:27)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18) {
  code: 'MODULE_NOT_FOUND',
  path: '/app/node_modules/@imazen/imageflow/package.json',
  requestPath: '@imazen/imageflow'
```

I'm using Ubuntu 18.04 Docker container with prebuilt library (downloaded from here https://github.com/imazen/imageflow/releases)

And installed nodejs 14.5.0

Is there something I'm doing wrong or is it the module issue?

Thanks, 
Oleksii

**Comment by anshulrgoyal** [comment]
Hi, I think we broke the package on the last build. I will fix it thanks for pointing out.

**Comment by anshulrgoyal** [comment]
I fixed the package and released a newer version. You can download it. I will close this issue. If the issue persist u can reopen it.

**Comment by aasiutin** [comment]
@anshulrgoyal  thanks a lot!
Could you also please advice on how to run it in Docker? I have the next error 
```
Error: /app/node_modules/@imazen/imageflow/native/index.node: invalid ELF header
```

the image is node:14.5-stretch

thanks,
Oleksii

**Comment by anshulrgoyal** [comment]
@aasiutin  I don't think this is an error from the package. May be native binding isn't downloaded properly.
This runs in docker without any problem https://github.com/anshulrgoyal/imageflow-now

**Comment by lilith** [comment]
@aasiutin Could you share the final Dockerfile you are using to build it? It may need `ENV PATH=/usr/local/cargo/bin:$PATH`

**Comment by lilith** [comment]
@aasiutin During package installation, do you get the message `Unable to download the required binary`?

**Comment by anshulrgoyal** [comment]
@aasiutin Did u got it working?

**Comment by aasiutin** [comment]
I’ve got it working, thanks!
One thing to note: you have to run 
npm install imageflow-node during the container run, not during the build. This way it downloads right node native binary. 

One more question: how hard it would be to update imageflow to the latest version (so it don’t have memory leaks)?

Guys, thanks a lot for your support!
Oleksii

**Comment by anshulrgoyal** [comment]
@lilith can u more about imageflow update. It depends on changes in core library.

**Comment by lilith** [comment]
The last release of Imageflow should fix the leak. We can release a node
update soon.

**Comment by aasiutin** [comment]
That would be great, thanks!

**Comment by anshulrgoyal** [comment]
I updated the imageflow-node. I will test it and release it tommorow

**Comment by anshulrgoyal** [comment]
@aasiutin I have published package with update libraries.

**Comment by anshulrgoyal** [comment]
I am closing this issue. If have a problem please try to open a separate issue it will help other users in future
